rootUrl: http://replaced.when.running
gridUrl: http://replaced.when.running

plugins:
  express: true
  sauce: true

browsers:
  chrome:
    platform: "WIN8"
    browserName: "chrome"
    version: "42"
  firefox:
    platform: WIN8
    browserName: "firefox"
    version: "37"
  ie:
    platform: VISTA
    browserName: "internet explorer"
    version: "11"