sudo: false
language: java
cache:
  directories:
      - node_modules
install: travis_retry npm install
jdk: oraclejdk8
script:
  - gulp lint:js
  - gulp lint:html
  - gulp clean
  - gulp gwt:validate
  - travis_retry gulp test:desktop
  - travis_retry gulp test:mobile
